<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Repository;

use CodePrimer\Tests\Entity\Post;
use CodePrimer\Tests\Entity\User;
use CodePrimer\Tests\Entity\Topic;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Psr\Log\LoggerInterface;

/**
 * Class PostRepository
 * Manipulates Post entities with the persistence layer.
 * @package CodePrimer\Tests\Repository
 * @method Post|null find($id, $lockMode = null, $lockVersion = null)
 * @method Post|null findOneBy(array $criteria, array $orderBy = null)
 * @method Post[]    findAll()
 * @method Post[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class PostRepository extends ServiceEntityRepository
{
    /** @var LoggerInterface */
    private $logger;

    /**
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Post::class);
    }

    /**
     * @required
     * @param LoggerInterface $logger
     */
    public function setLogger(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    /**
     * Retrieves a list of Post linked to a given User
     * @param User $author
     * @param bool $mostRecentFirst
     * @return Post[]
     */
    public function findAllByUser(User $author, bool $mostRecentFirst = true): array
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.author = :author')
            ->setParameter('author', $author)
            ->orderBy('u.created', $mostRecentFirst ? 'DESC' : 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Retrieves a list of Post linked to a given Topic
     * @param Topic $topic
     * @param bool $mostRecentFirst
     * @return Post[]
     */
    public function findAllByTopic(Topic $topic, bool $mostRecentFirst = true): array
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.topic = :topic')
            ->setParameter('topic', $topic)
            ->orderBy('u.created', $mostRecentFirst ? 'DESC' : 'ASC')
            ->getQuery()
            ->getResult();
    }

}
