<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Event;

use \DateTimeInterface;

/**
 * Class SchedulePost
 * Event triggered when user wants to schedule a post at a given time
 * @package CodePrimer\Tests\Event
 */
class SchedulePost
{
    /** @var string The post's unique ID in our system */
    protected $id = '';

    /** @var DateTimeInterface The time at which this post must be published */
    protected $scheduled;

    /**
     * SchedulePost default constructor
     * @var string $id The post's unique ID in our system
     * @var DateTimeInterface $scheduled The time at which this post must be published
     */
    public function __construct(
        string $id,
        DateTimeInterface $scheduled
    ) {
        $this->id = $id;
        $this->scheduled = $scheduled;
    }

    /**
     * @codeCoverageIgnore
     * @param string $id
     * @return SchedulePost
     */
    public function setId(string $id): SchedulePost
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @codeCoverageIgnore
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @codeCoverageIgnore
     * @param DateTimeInterface $scheduled
     * @return SchedulePost
     */
    public function setScheduled(DateTimeInterface $scheduled): SchedulePost
    {
        $this->scheduled = $scheduled;
        return $this;
    }

    /**
     * @codeCoverageIgnore
     * @return DateTimeInterface
     */
    public function getScheduled(): DateTimeInterface
    {
        return $this->scheduled;
    }

}
