/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package codeprimer.tests.entity;

/**
 * Class Post
 * Post created by the user
 * @package codeprimer.tests.entity
 */
public class Post
{
    /** The post's unique ID in our system */
    private String id = "";

    /** The post title */
    private String title = "";

    /** The post body */
    private String body = "";

    /** The time at which this post must be published */
    private Date scheduled = null;

    /** The user who created this post */
    private User author;

    /** The topic to which this post belongs */
    private Topic topic;

    /** Time at which the post was created */
    private Date created = null;

    /** Last time at which the post was updated */
    private Date updated = null;

    /**
     * Post default constructor
     * @param id The post's unique ID in our system
     * @param title The post title
     * @param body The post body
     * @param author The user who created this post
     * @param topic The topic to which this post belongs
     */
    public Post (
        String id,
        String title,
        String body,
        User author,
        Topic topic
    ) {
        this.id = id;
        this.title = title;
        this.body = body;
        this.author = author;
        this.topic = topic;
    }

    /**
     * @param id
     * @return Post
     */
    public Post setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * @return String
     */
    public String getId() {
        return this.id;
    }

    /**
     * @param title
     * @return Post
     */
    public Post setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * @return String
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * @param body
     * @return Post
     */
    public Post setBody(String body) {
        this.body = body;
        return this;
    }

    /**
     * @return String
     */
    public String getBody() {
        return this.body;
    }

    /**
     * @param scheduled
     * @return Post
     */
    public Post setScheduled(Date scheduled) {
        this.scheduled = scheduled;
        return this;
    }

    /**
     * @return Date
     */
    public Date getScheduled() {
        return this.scheduled;
    }

    /**
     * @param author
     * @return Post
     */
    public Post setAuthor(User author) {
        this.author = author;
        return this;
    }

    /**
     * @return User
     */
    public User getAuthor() {
        return this.author;
    }

    /**
     * @param topic
     * @return Post
     */
    public Post setTopic(Topic topic) {
        this.topic = topic;
        return this;
    }

    /**
     * @return Topic
     */
    public Topic getTopic() {
        return this.topic;
    }

    /**
     * @param created
     * @return Post
     */
    public Post setCreated(Date created) {
        this.created = created;
        return this;
    }

    /**
     * @return Date
     */
    public Date getCreated() {
        return this.created;
    }

    /**
     * @param updated
     * @return Post
     */
    public Post setUpdated(Date updated) {
        this.updated = updated;
        return this;
    }

    /**
     * @return Date
     */
    public Date getUpdated() {
        return this.updated;
    }

}
