/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package codeprimer.tests;

/**
 * Class Subscription
 * The subscription bought by a user to user our services
 * @package codeprimer.tests
 */
public class Subscription
{
    /** The user to which this subscription belongs */
    private User user;

    /** The plan subscribed by this user in our billing system */
    private String plan = "";

    /** The date at which the subscription must be renewed */
    private Date renewal;

    /** Time at which the post was created */
    private Date created = null;

    /** Last time at which the post was updated */
    private Date updated = null;

    /**
     * Subscription default constructor
     * @param user The user to which this subscription belongs
     * @param plan The plan subscribed by this user in our billing system
     * @param renewal The date at which the subscription must be renewed
     */
    public Subscription (
        User user,
        String plan,
        Date renewal
    ) {
        this.user = user;
        this.plan = plan;
        this.renewal = renewal;
    }

    /**
     * @param user
     * @return Subscription
     */
    public Subscription setUser(User user) {
        this.user = user;
        return this;
    }

    /**
     * @return User
     */
    public User getUser() {
        return this.user;
    }

    /**
     * @param plan
     * @return Subscription
     */
    public Subscription setPlan(String plan) {
        this.plan = plan;
        return this;
    }

    /**
     * @return String
     */
    public String getPlan() {
        return this.plan;
    }

    /**
     * @param renewal
     * @return Subscription
     */
    public Subscription setRenewal(Date renewal) {
        this.renewal = renewal;
        return this;
    }

    /**
     * @return Date
     */
    public Date getRenewal() {
        return this.renewal;
    }

    /**
     * @param created
     * @return Subscription
     */
    public Subscription setCreated(Date created) {
        this.created = created;
        return this;
    }

    /**
     * @return Date
     */
    public Date getCreated() {
        return this.created;
    }

    /**
     * @param updated
     * @return Subscription
     */
    public Subscription setUpdated(Date updated) {
        this.updated = updated;
        return this;
    }

    /**
     * @return Date
     */
    public Date getUpdated() {
        return this.updated;
    }

}
