/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package codeprimer.tests;

/**
 * Class Topic
 * A topic regroups a set of posts made by various authors
 * @package codeprimer.tests
 */
public class Topic
{
    /** The topic title */
    private String title = "";

    /** The topic description */
    private String description = null;

    /** List of authors who are allowed to post on this topic */
    private List<User> authors = null;

    /** List of posts published on this topic */
    private List<Post> posts = null;

    /** Time at which the post was created */
    private Date created = null;

    /** Last time at which the post was updated */
    private Date updated = null;

    /**
     * Topic default constructor
     * @param title The topic title
     */
    public Topic (
        String title
    ) {
        this.title = title;
    }

    /**
     * @param title
     * @return Topic
     */
    public Topic setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * @return String
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * @param description
     * @return Topic
     */
    public Topic setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * @return String
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * @param authors
     * @return Topic
     */
    public Topic setAuthors(List<User> authors) {
        this.author = authors;
        return this;
    }

    /**
     * @return List<User>
     */
    public List<User> getAuthors() {
        return this.author;
    }

    /**
     * @param posts
     * @return Topic
     */
    public Topic setPosts(List<Post> posts) {
        this.post = posts;
        return this;
    }

    /**
     * @return List<Post>
     */
    public List<Post> getPosts() {
        return this.post;
    }

    /**
     * @param created
     * @return Topic
     */
    public Topic setCreated(Date created) {
        this.created = created;
        return this;
    }

    /**
     * @return Date
     */
    public Date getCreated() {
        return this.created;
    }

    /**
     * @param updated
     * @return Topic
     */
    public Topic setUpdated(Date updated) {
        this.updated = updated;
        return this;
    }

    /**
     * @return Date
     */
    public Date getUpdated() {
        return this.updated;
    }

}
