<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Entity;

use \DateTimeInterface;

/**
 * Class UserStats
 * Simple statistics about the user
 * @package CodePrimer\Tests\Entity
 */
class UserStats
{
    /** @var DateTimeInterface|null First time the user logged in the system */
    protected $firstLogin = null;

    /** @var DateTimeInterface|null Last time the user logged in the system */
    protected $lastLogin = null;

    /** @var int|null Number of time the user logged in the system */
    protected $loginCount = null;

    /**
     * @codeCoverageIgnore
     * @param DateTimeInterface|null $firstLogin
     * @return UserStats
     */
    public function setFirstLogin(?DateTimeInterface $firstLogin): UserStats
    {
        $this->firstLogin = $firstLogin;
        return $this;
    }

    /**
     * @codeCoverageIgnore
     * @return DateTimeInterface|null
     */
    public function getFirstLogin(): ?DateTimeInterface
    {
        return $this->firstLogin;
    }

    /**
     * @codeCoverageIgnore
     * @param DateTimeInterface|null $lastLogin
     * @return UserStats
     */
    public function setLastLogin(?DateTimeInterface $lastLogin): UserStats
    {
        $this->lastLogin = $lastLogin;
        return $this;
    }

    /**
     * @codeCoverageIgnore
     * @return DateTimeInterface|null
     */
    public function getLastLogin(): ?DateTimeInterface
    {
        return $this->lastLogin;
    }

    /**
     * @codeCoverageIgnore
     * @param int|null $loginCount
     * @return UserStats
     */
    public function setLoginCount($loginCount): UserStats
    {
        $this->loginCount = intval($loginCount);
        return $this;
    }

    /**
     * @codeCoverageIgnore
     * @return int|null
     */
    public function getLoginCount(): ?int
    {
        return $this->loginCount;
    }

}
