/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package codeprimer.tests.entity;

/**
 * Class Metadata
 * Variable set of extra information
 * @package codeprimer.tests.entity
 */
public class Metadata
{
    /** The name to uniquely identify this metadata */
    private String name = "";

    /** The value associated with this metadata */
    private String value = "";

    /**
     * Metadata default constructor
     * @param name The name to uniquely identify this metadata
     * @param value The value associated with this metadata
     */
    public Metadata (
        String name,
        String value
    ) {
        this.name = name;
        this.value = value;
    }

    /**
     * @param name
     * @return Metadata
     */
    public Metadata setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * @return String
     */
    public String getName() {
        return this.name;
    }

    /**
     * @param value
     * @return Metadata
     */
    public Metadata setValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * @return String
     */
    public String getValue() {
        return this.value;
    }

}
