/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package codeprimer.tests.entity;

import codeprimer.tests.dataset.UserStatus;

/**
 * Class User
 * This entity represents a user
 * @package codeprimer.tests.entity
 */
public class User
{
    /** The user's unique ID in our system */
    private String id = "";

    /** User first name */
    private String firstName = null;

    /** User last name */
    private String lastName = null;

    /** The name used to identify this user publicly on the site */
    private String nickname = null;

    /** User email address */
    private String email = "";

    /** User password */
    private String password = "";

    /** The date and time at which this user was created */
    private Date created = null;

    /** The date and time at which this user was updated */
    private Date updated = null;

    /** The ID of this user in our external CRM */
    private String crmId = null;

    /** The code required to validate the user's account */
    private String activationCode = null;

    /** User login statistics */
    private UserStats stats = null;

    /** The plan to which the user is subscribed */
    private Subscription subscription = null;

    /** Extra information about the user */
    private List<Metadata> metadata = null;

    /** Blog posts created by this user */
    private List<Post> posts = null;

    /** List of topics this user to allowed to create posts for */
    private List<Topic> topics = null;

    /** Current status of the user */
    private UserStatus status = null;

    /**
     * User default constructor
     * @param id The user's unique ID in our system
     * @param email User email address
     * @param password User password
     */
    public User (
        String id,
        String email,
        String password
    ) {
        this.id = id;
        this.email = email;
        this.password = password;
    }

    /**
     * @param id
     * @return User
     */
    public User setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * @return String
     */
    public String getId() {
        return this.id;
    }

    /**
     * @param firstName
     * @return User
     */
    public User setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * @return String
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * @param lastName
     * @return User
     */
    public User setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * @return String
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * @param nickname
     * @return User
     */
    public User setNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * @return String
     */
    public String getNickname() {
        return this.nickname;
    }

    /**
     * @param email
     * @return User
     */
    public User setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * @return String
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * @param password
     * @return User
     */
    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * @return String
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * @param created
     * @return User
     */
    public User setCreated(Date created) {
        this.created = created;
        return this;
    }

    /**
     * @return Date
     */
    public Date getCreated() {
        return this.created;
    }

    /**
     * @param updated
     * @return User
     */
    public User setUpdated(Date updated) {
        this.updated = updated;
        return this;
    }

    /**
     * @return Date
     */
    public Date getUpdated() {
        return this.updated;
    }

    /**
     * @param crmId
     * @return User
     */
    public User setCrmId(String crmId) {
        this.crmId = crmId;
        return this;
    }

    /**
     * @return String
     */
    public String getCrmId() {
        return this.crmId;
    }

    /**
     * @param activationCode
     * @return User
     */
    public User setActivationCode(String activationCode) {
        this.activationCode = activationCode;
        return this;
    }

    /**
     * @return String
     */
    public String getActivationCode() {
        return this.activationCode;
    }

    /**
     * @param stats
     * @return User
     */
    public User setStats(UserStats stats) {
        this.stat = stats;
        return this;
    }

    /**
     * @return UserStats
     */
    public UserStats getStats() {
        return this.stat;
    }

    /**
     * @param subscription
     * @return User
     */
    public User setSubscription(Subscription subscription) {
        this.subscription = subscription;
        return this;
    }

    /**
     * @return Subscription
     */
    public Subscription getSubscription() {
        return this.subscription;
    }

    /**
     * @param metadata
     * @return User
     */
    public User setMetadata(List<Metadata> metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * @return List<Metadata>
     */
    public List<Metadata> getMetadata() {
        return this.metadata;
    }

    /**
     * @param posts
     * @return User
     */
    public User setPosts(List<Post> posts) {
        this.post = posts;
        return this;
    }

    /**
     * @return List<Post>
     */
    public List<Post> getPosts() {
        return this.post;
    }

    /**
     * @param topics
     * @return User
     */
    public User setTopics(List<Topic> topics) {
        this.topic = topics;
        return this;
    }

    /**
     * @return List<Topic>
     */
    public List<Topic> getTopics() {
        return this.topic;
    }

    /**
     * @param status
     * @return User
     */
    public User setStatus(UserStatus status) {
        this.status = status;
        return this;
    }

    /**
     * @return UserStatus
     */
    public UserStatus getStatus() {
        return this.status;
    }

}
