<?php


namespace CodePrimer\Template;


use Twig\Extension\AbstractExtension;

class Template
{
    /** @var string The name of the template */
    private $name;

    /** @var Artifact The artifact that will be generated by this template */
    private $artifact;

    /** @var AbstractExtension[] The list of extensions required by this template */
    private $extensions;

    /**
     * Template constructor.
     * @param string $name
     * @param Artifact $artifact
     * @param AbstractExtension[] $extensions
     */
    public function __construct(string $name, Artifact $artifact, array $extensions = [])
    {
        $this->name = $name;
        $this->artifact = $artifact;
        $this->extensions = $extensions;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return Artifact
     */
    public function getArtifact(): Artifact
    {
        return $this->artifact;
    }

    /**
     * @return AbstractExtension[]
     */
    public function getExtensions(): array
    {
        return $this->extensions;
    }
}
