<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Event;

/**
 * Class LoginRequest
 * Event triggered when user wants to login with the application
 * @package CodePrimer\Tests\Event
 */
class LoginRequest
{
    /** @var string  */
    protected $email;

    /** @var string  */
    protected $password;

    /**
     * LoginRequest default constructor
     */
    public function __construct(
    ) {
    }

}
