<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Event;

/**
 * Class LoginRequest
 * Event triggered when user wants to login with the application
 * @package CodePrimer\Tests\Event
 */
class LoginRequest
{
    /** @var string User email address */
    protected $email;

    /** @var string User password */
    protected $password;

    /**
     * LoginRequest default constructor
     * @var string $email User email address
     * @var string $password User password
     */
    public function __construct(
        string $email,
        string $password
    ) {
        $this->email = $email;
        $this->password = $password;
    }

    /**
     * @codeCoverageIgnore
     * @param string $email
     * @return LoginRequest
     */
    public function setEmail(string $email): LoginRequest
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @codeCoverageIgnore
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @codeCoverageIgnore
     * @param string $password
     * @return LoginRequest
     */
    public function setPassword(string $password): LoginRequest
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @codeCoverageIgnore
     * @return string
     */
    public function getPassword(): string
    {
        return $this->password;
    }

}
