<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Event;

/**
 * Class RegistrationRequest
 * Event triggered when user wants to register with the application
 * @package CodePrimer\Tests\Event
 */
class RegistrationRequest
{
    /** @var string  */
    protected $email;

    /** @var string  */
    protected $password;

    /** @var string  */
    protected $firstName = null;

    /** @var string  */
    protected $lastName = null;

    /** @var string  */
    protected $nickname = null;

    /**
     * RegistrationRequest default constructor
     */
    public function __construct(
    ) {
    }

}
