<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Event;

    use \DateTimeInterface;

/**
 * Class SchedulePost
 * Event triggered when user wants to schedule a post at a given time
 * @package CodePrimer\Tests\Event
 */
class SchedulePost
{
    /** @var string  */
    protected $id;

    /** @var string  */
    protected $scheduled;

    /**
     * SchedulePost default constructor
     */
    public function __construct(
    ) {
    }

}
