<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Event;

/**
 * Class SimpleEvent
 * 
 * @package CodePrimer\Tests\Event
 */
class SimpleEvent
{
    /**
     * SimpleEvent default constructor
     */
    public function __construct(
    ) {
    }

}
