<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Model;

use \DateTimeInterface;

/**
 * Class Post
 * Post created by the user
 * @package CodePrimer\Tests\Model
 */
class Post
{
    /** @var string The post's unique ID in our system */
    protected $id = '';

    /** @var string The post title */
    protected $title = '';

    /** @var string The post body */
    protected $body = '';

    /** @var DateTimeInterface|null The time at which this post must be published */
    protected $scheduled = null;

    /** @var User The user who created this post */
    protected $author;

    /** @var Topic The topic to which this post belongs */
    protected $topic;

    /** @var DateTimeInterface|null Time at which the post was created */
    protected $created = null;

    /** @var DateTimeInterface|null Last time at which the post was updated */
    protected $updated = null;

    /**
     * Post default constructor
     * @var string $id The post's unique ID in our system
     * @var string $title The post title
     * @var string $body The post body
     * @var User $author The user who created this post
     * @var Topic $topic The topic to which this post belongs
     */
    public function __construct(
        string $id,
        string $title,
        string $body,
        User $author,
        Topic $topic
    ) {
        $this->id = $id;
        $this->title = $title;
        $this->body = $body;
        $this->author = $author;
        $this->topic = $topic;
    }

    /**
     * @param string $id
     * @return Post
     */
    public function setId(string $id): Post
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @param string $title
     * @return Post
     */
    public function setTitle(string $title): Post
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @param string $body
     * @return Post
     */
    public function setBody(string $body): Post
    {
        $this->body = $body;
        return $this;
    }

    /**
     * @return string
     */
    public function getBody(): string
    {
        return $this->body;
    }

    /**
     * @param DateTimeInterface|null $scheduled
     * @return Post
     */
    public function setScheduled(?DateTimeInterface $scheduled): Post
    {
        $this->scheduled = $scheduled;
        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getScheduled(): ?DateTimeInterface
    {
        return $this->scheduled;
    }

    /**
     * @param User $author
     * @return Post
     */
    public function setAuthor(User $author): Post
    {
        $this->author = $author;
        return $this;
    }

    /**
     * @return User
     */
    public function getAuthor(): User
    {
        return $this->author;
    }

    /**
     * @param Topic $topic
     * @return Post
     */
    public function setTopic(Topic $topic): Post
    {
        $this->topic = $topic;
        return $this;
    }

    /**
     * @return Topic
     */
    public function getTopic(): Topic
    {
        return $this->topic;
    }

    /**
     * @param DateTimeInterface|null $created
     * @return Post
     */
    public function setCreated(?DateTimeInterface $created): Post
    {
        $this->created = $created;
        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getCreated(): ?DateTimeInterface
    {
        return $this->created;
    }

    /**
     * @param DateTimeInterface|null $updated
     * @return Post
     */
    public function setUpdated(?DateTimeInterface $updated): Post
    {
        $this->updated = $updated;
        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getUpdated(): ?DateTimeInterface
    {
        return $this->updated;
    }

}
