<?php
/*
 * This file has been generated by CodePrimer.io
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CodePrimer\Tests\Entity;

use \DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class UserStats
 * Simple statistics about the user
 * @package CodePrimer\Tests\Entity
 * @ORM\Entity(repositoryClass="App\Repository\UserStatsRepository")
 * @ORM\Table(name="user_stats")
 */
class UserStats
{
    /**
     * @var DateTimeInterface|null First time the user logged in the system
     * @ORM\Column(name="first_login", type="datetime", nullable=true)
     */
    protected $firstLogin = null;

    /**
     * @var DateTimeInterface|null Last time the user logged in the system
     * @ORM\Column(name="last_login", type="datetime", nullable=true)
     */
    protected $lastLogin = null;

    /**
     * @var int|null Number of time the user logged in the system
     * @ORM\Column(name="login_count", type="bigint", nullable=true)
     */
    protected $loginCount = null;

    /**
     * @var string DB unique identifier field
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(name="id", type="string", length=36)
     */
    protected $id = '';

    /**
     * UserStats default constructor
     * @var string $id DB unique identifier field
     */
    public function __construct(
        string $id
    ) {
        $this->id = $id;
    }

    /**
     * @param DateTimeInterface|null $firstLogin
     * @return UserStats
     */
    public function setFirstLogin(?DateTimeInterface $firstLogin): UserStats
    {
        $this->firstLogin = $firstLogin;
        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getFirstLogin(): ?DateTimeInterface
    {
        return $this->firstLogin;
    }

    /**
     * @param DateTimeInterface|null $lastLogin
     * @return UserStats
     */
    public function setLastLogin(?DateTimeInterface $lastLogin): UserStats
    {
        $this->lastLogin = $lastLogin;
        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getLastLogin(): ?DateTimeInterface
    {
        return $this->lastLogin;
    }

    /**
     * @param int|null $loginCount
     * @return UserStats
     */
    public function setLoginCount($loginCount): UserStats
    {
        $this->loginCount = intval($loginCount);
        return $this;
    }

    /**
     * @return int|null
     */
    public function getLoginCount(): ?int
    {
        return $this->loginCount;
    }

    /**
     * @param string $id
     * @return UserStats
     */
    public function setId(string $id): UserStats
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

}
